#!/bin/sh /etc/rc.common
# Launch BitmaskVPN
# Copyright (C) 2021 Kali Kaneko

START=10
STOP=15

USE_PROCD=1

reload_service() {
        procd_send_signal /usr/bin/bitmaskd
}

start_service() {
        mkdir -m 0700 -p /var/log/bitmask
        procd_open_instance
        procd_set_param command /usr/bin/bitmaskd
        procd_set_param respawn
        procd_close_instance
}
