#!/bin/sh
# Switch LEAP VPN On/Off
# To be placed in /etc/rc.button/BTN_0

is_ar750=$(/bin/grep -c 'gl-ar750' /etc/board.json)
if [ "$is_ar750" = "3" ]; then
  toggle_on=$(/bin/grep -c 'sw1.*hi' /sys/kernel/debug/gpio)
fi

is_mt300n=$(/bin/grep -c 'gl-mt300n-v2' /etc/board.json)
if [ "$is_mt300n" = "3" ]; then
  toggle_on=$(/bin/grep -c 'gpio-0.*hi' /sys/kernel/debug/gpio)
fi

if [ "$toggle_on" = "1" ]; then
  curl localhost:8080/start
fi
if [ "$toggle_on" = "0" ]; then
  curl localhost:8080/stop
fi
